### ISSUE TITLE
Enhancement shaman output loop has stopped and get error

### ISSUE THREAD

**Issue by maioro** [kaminaris/MaxDps-Shaman#15]
Does the addon now support 11.0.2 at level 80?
in 11.0.2.56196 version game still outputs a loop error
 

158x MaxDps_Shaman/Specialization/Enhancement.lua:221: attempt to compare number with boolean
[string "@MaxDps_Shaman/Specialization/Enhancement.lua"]:221: in function `single'
[string "@MaxDps_Shaman/Specialization/Enhancement.lua"]:535: in function `callaction'
[string "@MaxDps_Shaman/Specialization/Enhancement.lua"]:605: in function `NextSpell'
[string "@MaxDps/Core.lua"]:7035: in function `?'
[string "@Broker_DurabilityInfo/Libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <...er_DurabilityInfo/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Talent 

CcQA6DE2ZxOD3n18X41tWLU5RNzMzyMDGzMDzMzshlZMDAAAAAAAAAAAAAAAAAAzykBmlFzMzwYmZ2wyMzEsMWGzMAAzA

**Comment by doadin** [comment]
All specs except the three evokes specs and fire mage are now up to date for 11.0.2. As you can see though some may need a few bugs worked out, most have been released for a couple weeks now. Shaman I just updated like last night. While support is in place for 80 I do need some more spell data something should get easy now that launch is happening. I am not at my computer now but will check this out later. Thanks for posting your talent import string as most issues come from talents I didn't use in testing.

**Comment by doadin** [comment]
after this commit https://github.com/kaminaris/MaxDps-Shaman/commit/2958c3478028c3c7a974f9bccb9e6a1e171d9039 I tested with the talents provided and got no errors in single target nor 5 target(aoe), if you have any suggestions or other issues please let me know!
