### ISSUE TITLE
Minor Rotation issue 

### ISSUE THREAD

**Issue by f3rr311** [kaminaris/MaxDps-Shaman#7]
![image](https://user-images.githubusercontent.com/14023914/201510780-9092d863-2bf4-4aef-b2b8-cd741aa4cac4.png)

When using Single Target and AOE build available at https://www.icy-veins.com/wow/elemental-shaman-pve-dps-spec-builds-talents 
MAXDPS gets stuck asking for earthquake which has no proc'ed and for several other skill presses if just keeps waiting and is stuck waiting.

I am not sure if your rotation is using a different talent build and earthquake is available sooner I am willing to test if you have need of that.

These are the rotations I think they are expecting
https://www.icy-veins.com/wow/elemental-shaman-pve-dps-rotation-cooldowns-abilities

**Comment by codengine** [comment]
Hi, which version of the Shaman module do you use? There was an update this night.

**Comment by f3rr311** [comment]
This was with the latest update

**Comment by codengine** [comment]
I've created an updated version which not only improves the handling of earthquake but also includes Icefury and Elemental Blast (if skilled) in the rotation.

Could you please try that one for me?
[MaxDps-Shaman-master.zip](https://github.com/kaminaris/MaxDps-Shaman/files/10016209/MaxDps-Shaman-master.zip)
